mock = {
    "match_result": {
        "overall_score": 5,
        "skills_score": 6,
        "experience_score": 4,
        "matched_skills": [
            "Python",
            "Java",
            "C++",
            "Redux",
            "Deployment",
            "Reliability Practices",
            "SQL",
            "NoSQL",
            "Collaboration",
            "Requirement Definition",
            "Product Feature Design",
            "Written Communication",
            "Verbal Communication",
            "Technical Documentation",
            "Full Stack Development",
            "Distributed Systems",
            "Scalable Systems",
            "High-Performance Systems",
        ],
        "missing_skills": [
            "Go",
            "GraphQL",
            "Monitoring",
            "MySQL",
            "Cassandra",
            "Spark SQL",
            "Presto",
            "BaseUI",
            "Styletron",
            "Jest",
            "Playwright",
        ],
        "summary": "Marc possesses a strong technical foundation in Python, Java, and C++, with practical experience in Redux, SQL/NoSQL databases, and cloud platforms, matching many core technical requirements. While the candidate's software engineering tenure is approximately 1.5 years, falling short of the 4+ years required, their experience at TomTom demonstrates high impact, leadership potential, and delivery on significant projects.",
    },
    "ats_tips": {
        "tips": [
            "Add Go and GraphQL to your skills section if you have any exposure",
            "Quantify achievements in your experience entries (e.g., '20% latency reduction')",
            "Include monitoring/observability tools (Prometheus, Grafana) if applicable",
            "Mention MySQL or Cassandra experience if relevant to past work",
            "Add keywords: distributed systems, scalable architecture, high performance",
        ]
    },
    "jd_data": {
        "job_title": "Senior Software Engineer",
        "company": "Uber",
        "required_skills": [
            "Python",
            "Java",
            "Go",
            "GraphQL",
            "MySQL",
            "Cassandra",
            "Spark SQL",
        ],
        "preferred_skills": [
            "Distributed Systems",
            "Scalable Systems",
            "High-Performance Systems",
        ],
        "nice_to_have": ["BaseUI", "Styletron", "Jest", "Playwright"],
        "experience_required": "4+ years",
        "keywords": [
            "backend",
            "distributed",
            "scalable",
            "high-performance",
            "full-stack",
        ],
    },
}


mock2 = {
    "match_result": {
        "overall_score": 8,
        "skills_score": 7,
        "experience_score": 5,
        "matched_skills": [
            "Python",
            "FastAPI",
            "Django",
            "PostgreSQL",
            "Docker",
            "Kubernetes",
            "AWS",
            "REST APIs",
            "CI/CD",
            "GitHub Actions",
            "Microservices",
            "Query optimization",
            "Mentoring",
            "Senior Backend Engineer experience",
        ],
        "missing_skills": [
            "Kafka",
            "RabbitMQ",
            "Go",
            "GraphQL",
            "Terraform",
        ],
        "summary": "John Doe is a highly suitable candidate with over 5 years of backend engineering experience, including a senior role, and strong proficiency in Python (FastAPI, Django), PostgreSQL, Docker, Kubernetes, and AWS. He demonstrates excellent alignment with core technical requirements like REST APIs, microservices, and CI/CD, and has leadership experience. While he lacks explicit experience with message queues (Kafka, RabbitMQ), Go, GraphQL, and Terraform, his foundational skills and proven track record make him an excellent fit.",
    },
    "ats_tips": {
        "tips": [
            "Add Kafka or RabbitMQ to your skills if you have any exposure to message queues",
            "Include Terraform or IaC tools if you have used them in past projects",
            "Mention open-source contributions or personal projects on GitHub",
            "Highlight specific metrics from CI/CD pipelines you have built",
            "Add GraphQL experience if applicable, even if minimal",
        ]
    },
    "jd_data": {
        "job_title": "Senior Backend Engineer",
        "company": "TechCorp",
        "required_skills": [
            "Python",
            "FastAPI",
            "Django",
            "PostgreSQL",
            "Docker",
            "Kubernetes",
            "AWS",
        ],
        "preferred_skills": ["Kafka", "RabbitMQ", "Go", "GraphQL", "Terraform"],
        "nice_to_have": ["Open-source contributions"],
        "experience_required": "5+ years",
        "keywords": [
            "backend",
            "microservices",
            "REST API",
            "CI/CD",
            "cloud",
            "senior",
        ],
    },
}

mock3 = {
    "match_result": {
        "overall_score": 3,
        "skills_score": 3,
        "experience_score": 4,
        "matched_skills": [
            "Python",
            "Linux",
            "AWS",
            "Docker",
            "GitHub",
            "Bash scripting",
            "Deployment",
        ],
        "missing_skills": [
            "Kubernetes",
            "Terraform",
            "Ansible",
            "Jenkins",
            "Prometheus",
            "Grafana",
            "ArgoCD",
            "Helm",
            "CI/CD pipelines",
            "Infrastructure as Code",
            "Monitoring tools",
            "Log aggregation",
            "ELK stack",
        ],
        "summary": "Sarah has foundational experience with Python, Linux, and AWS, with basic Docker knowledge. However, her background is primarily in frontend development with limited DevOps infrastructure exposure. She lacks critical DevOps skills including Kubernetes orchestration, Infrastructure as Code tools (Terraform, Ansible), CI/CD pipeline management (Jenkins), and observability solutions (Prometheus, Grafana). Significant upskilling would be required for this DevOps engineer role.",
    },
    "ats_tips": {
        "tips": [
            "Learn and add Kubernetes to your skills—it's essential for modern DevOps roles",
            "Take a course on Terraform or CloudFormation for Infrastructure as Code",
            "Gain hands-on experience with Jenkins or GitLab CI for pipeline automation",
            "Add Prometheus and Grafana experience to your monitoring toolkit",
            "Document any CI/CD or automation projects, even if small-scale",
            "Consider learning Ansible for configuration management",
        ]
    },
    "jd_data": {
        "job_title": "DevOps Engineer",
        "company": "CloudScale Inc",
        "required_skills": [
            "Kubernetes",
            "Terraform",
            "Docker",
            "AWS",
            "CI/CD pipelines",
            "Bash scripting",
        ],
        "preferred_skills": [
            "Ansible",
            "Jenkins",
            "Prometheus",
            "Grafana",
            "ArgoCD",
            "Infrastructure as Code",
        ],
        "nice_to_have": ["Helm", "ELK stack", "Log aggregation"],
        "experience_required": "3+ years",
        "keywords": [
            "devops",
            "kubernetes",
            "infrastructure",
            "automation",
            "cloud",
            "ci-cd",
        ],
    },
}
