mock = {
    "match_result": {
        "overall_score": 5,
        "skills_score": 6,
        "experience_score": 4,
        "matched_skills": [
            "Python",
            "Java",
            "C++",
            "Redux",
            "Deployment",
            "Reliability Practices",
            "SQL",
            "NoSQL",
            "Collaboration",
            "Requirement Definition",
            "Product Feature Design",
            "Written Communication",
            "Verbal Communication",
            "Technical Documentation",
            "Full Stack Development",
            "Distributed Systems",
            "Scalable Systems",
            "High-Performance Systems",
        ],
        "missing_skills": [
            "Go",
            "GraphQL",
            "Monitoring",
            "MySQL",
            "Cassandra",
            "Spark SQL",
            "Presto",
            "BaseUI",
            "Styletron",
            "Jest",
            "Playwright",
        ],
        "summary": "Marc possesses a strong technical foundation in Python, Java, and C++, with practical experience in Redux, SQL/NoSQL databases, and cloud platforms, matching many core technical requirements. While the candidate's software engineering tenure is approximately 1.5 years, falling short of the 4+ years required, their experience at TomTom demonstrates high impact, leadership potential, and delivery on significant projects.",
    },
    "ats_tips": {},
}


mock2 = {
    "match_result": {
        "overall_score": 8,
        "skills_score": 7,
        "experience_score": 5,
        "matched_skills": [
            "Python",
            "FastAPI",
            "Django",
            "PostgreSQL",
            "Docker",
            "Kubernetes",
            "AWS",
            "REST APIs",
            "CI/CD",
            "GitHub Actions",
            "Microservices",
            "Query optimization",
            "Mentoring",
            "Senior Backend Engineer experience",
        ],
        "missing_skills": [
            "Kafka",
            "RabbitMQ",
            "Go",
            "GraphQL",
            "Terraform",
            "Open-source contributions",
        ],
        "summary": "John Doe is a highly suitable candidate with over 5 years of backend engineering experience, including a senior role, and strong proficiency in Python (FastAPI, Django), PostgreSQL, Docker, Kubernetes, and AWS. He demonstrates excellent alignment with core technical requirements like REST APIs, microservices, and CI/CD, and has leadership experience. While he lacks explicit experience with message queues (Kafka, RabbitMQ), Go, GraphQL, and Terraform, his foundational skills and proven track record make him an excellent fit.",
    },
    "ats_tips": {},
}