mock = {
    "match_result": {
        "overall_score": 5,
        "skills_score": 6,
        "experience_score": 4,
        "matched_skills": [
            "Python",
            "Java",
            "C++",
            "Redux",
            "Deployment",
            "Reliability Practices",
            "SQL",
            "NoSQL",
            "Collaboration",
            "Requirement Definition",
            "Product Feature Design",
            "Written Communication",
            "Verbal Communication",
            "Technical Documentation",
            "Full Stack Development",
            "Distributed Systems",
            "Scalable Systems",
            "High-Performance Systems",
        ],
        "missing_skills": [
            "Go",
            "GraphQL",
            "Monitoring",
            "MySQL",
            "Cassandra",
            "Spark SQL",
            "Presto",
            "BaseUI",
            "Styletron",
            "Jest",
            "Playwright",
        ],
        "summary": "Marc possesses a strong technical foundation in Python, Java, and C++, with practical experience in Redux, SQL/NoSQL databases, and cloud platforms, matching many core technical requirements. While the candidate's software engineering tenure is approximately 1.5 years, falling short of the 4+ years required, their experience at TomTom demonstrates high impact, leadership potential, and delivery on significant projects.",
    },
    "ats_tips": {
        "tips": [
            "Add Go and GraphQL to your skills section if you have any exposure",
            "Include monitoring/observability tools (Prometheus, Grafana) if applicable",
            "Mention MySQL or Cassandra experience if relevant to past work",
            "Add keywords: distributed systems, scalable architecture, high performance",
        ]
    },
    "jd_data": {
        "job_title": "Senior Software Engineer",
        "company": "AnyCompany",
        "required_skills": [
            "Python",
            "Java",
            "Go",
            "GraphQL",
            "MySQL",
            "Cassandra",
            "Spark SQL",
        ],
        "preferred_skills": [
            "Distributed Systems",
            "Scalable Systems",
            "High-Performance Systems",
        ],
        "nice_to_have": ["BaseUI", "Styletron", "Jest", "Playwright"],
        "experience_required": "4+ years",
        "keywords": [
            "backend",
            "distributed",
            "scalable",
            "high-performance",
            "full-stack",
        ],
    },
}


mock2 = {
    "match_result": {
        "overall_score": 8,
        "skills_score": 7,
        "experience_score": 5,
        "matched_skills": [
            "Python",
            "FastAPI",
            "Django",
            "PostgreSQL",
            "Docker",
            "Kubernetes",
            "AWS",
            "REST APIs",
            "CI/CD",
            "GitHub Actions",
            "Microservices",
            "Query optimization",
            "Mentoring",
            "Senior Backend Engineer experience",
        ],
        "missing_skills": [
            "Kafka",
            "RabbitMQ",
            "Go",
            "GraphQL",
            "Terraform",
        ],
        "summary": "John Doe is a highly suitable candidate with over 5 years of backend engineering experience, including a senior role, and strong proficiency in Python (FastAPI, Django), PostgreSQL, Docker, Kubernetes, and AWS. He demonstrates excellent alignment with core technical requirements like REST APIs, microservices, and CI/CD, and has leadership experience. While he lacks explicit experience with message queues (Kafka, RabbitMQ), Go, GraphQL, and Terraform, his foundational skills and proven track record make him an excellent fit.",
    },
    "ats_tips": {
        "tips": [
            "Include Terraform or IaC tools if you have used them in past projects",
            "Mention open-source contributions or personal projects on GitHub",
            "Add GraphQL experience if applicable, even if minimal",
        ]
    },
    "jd_data": {
        "job_title": "Senior Backend Engineer",
        "company": "TechCorp",
        "required_skills": [
            "Python",
            "FastAPI",
            "Django",
            "PostgreSQL",
            "Docker",
            "Kubernetes",
            "AWS",
        ],
        "preferred_skills": ["Kafka", "RabbitMQ", "Go", "GraphQL", "Terraform"],
        "nice_to_have": ["Open-source contributions"],
        "experience_required": "5+ years",
        "keywords": [
            "backend",
            "microservices",
            "REST API",
            "CI/CD",
            "cloud",
            "senior",
        ],
    },
}

mock3 = {
    "match_result": {
        "overall_score": 9,
        "skills_score": 9,
        "experience_score": 8,
        "matched_skills": [
            "Kubernetes",
            "Terraform",
            "Ansible",
            "Jenkins",
            "Prometheus",
            "Grafana",
            "ArgoCD",
            "Helm",
            "CI/CD pipelines",
            "Infrastructure as Code",
            "Monitoring tools",
            "Log aggregation",
            "ELK stack",
            "Docker",
            "AWS",
            "Python",
            "Bash scripting",
            "GitActions",
            "Configuration Management",
            "Automation",
        ],
        "missing_skills": [
            "Vault",
            "Consul",
            "New Relic",
        ],
        "summary": "Sarah is an exceptional DevOps engineer with 6+ years of hands-on experience in Kubernetes orchestration, Terraform IaC, and Jenkins CI/CD pipeline automation. She demonstrates mastery across the entire DevOps stack including Prometheus/Grafana monitoring, ArgoCD GitOps, Ansible configuration management, and ELK logging solutions. Her proven expertise in AWS cloud infrastructure, Docker containerization, and shell scripting aligns perfectly with all core requirements. She would be an immediate high-impact hire requiring minimal onboarding.",
    },
    "ats_tips": {
        "tips": [
            "Your Kubernetes expertise is highlighted prominently—excellent alignment with role",
            "CI/CD pipeline projects showcase strong technical depth",
        ]
    },
    "jd_data": {
        "job_title": "Senior DevOps Engineer",
        "company": "AnyTech",
        "required_skills": [
            "Kubernetes",
            "Terraform",
            "Docker",
            "AWS",
            "CI/CD pipelines",
            "Bash scripting",
        ],
        "preferred_skills": [
            "Ansible",
            "Jenkins",
            "Prometheus",
            "Grafana",
            "ArgoCD",
            "Infrastructure as Code",
        ],
        "nice_to_have": ["Helm", "ELK stack", "Log aggregation"],
        "experience_required": "6+ years",
        "keywords": [
            "devops",
            "kubernetes",
            "infrastructure",
            "automation",
            "cloud",
            "ci-cd",
            "GitActions",
        ],
    },
}
