"""add user_profiles applications application_comments

Revision ID: 0e168729f088
Revises: 
Create Date: 2026-03-23 12:23:49.673788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e168729f088'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jd_source', sa.Text(), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('match_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ats_tips', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'rejected', 'accepted', name='applicationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cv_text', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('application_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('general', 'company', 'interview', 'qa', name='commenttype'), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_comments_application_id'), 'application_comments', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_comments_id'), 'application_comments', ['id'], unique=False)
    op.create_index(op.f('ix_application_comments_user_id'), 'application_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_comments_user_id'), table_name='application_comments')
    op.drop_index(op.f('ix_application_comments_id'), table_name='application_comments')
    op.drop_index(op.f('ix_application_comments_application_id'), table_name='application_comments')
    op.drop_table('application_comments')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    sa.Enum(name='applicationstatus').drop(op.get_bind())
    sa.Enum(name='commenttype').drop(op.get_bind())
    # ### end Alembic commands ###
