"""add daily analysis limit to user_profiles

Revision ID: 2456fe554030
Revises: 9be62dc6375d
Create Date: 2026-04-13 16:39:49.956154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2456fe554030'
down_revision: Union[str, Sequence[str], None] = '9be62dc6375d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('daily_analyses_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_profiles', sa.Column('daily_analyses_reset_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'daily_analyses_reset_date')
    op.drop_column('user_profiles', 'daily_analyses_used')
    # ### end Alembic commands ###
