"""add jd_type to applications

Revision ID: 92ad82942728
Revises: f7bdceb76e84
Create Date: 2026-03-24 13:03:08.833543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ad82942728'
down_revision: Union[str, Sequence[str], None] = 'f7bdceb76e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('jd_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'jd_type')
    # ### end Alembic commands ###
